### ISSUE TITLE
prompt超出长度限制报错

### ISSUE THREAD

**Issue by KeyToon9** [Soulter/QQChannelChatGPT#1]
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4569 tokens (3545 in your prompt; 1024 for the completion). Please reduce your prompt; or completion length.

**Comment by Soulter** [comment]
感谢提出issue~
这个是由于gpt3的限制导致的，gpt3模型限制最大tokens为4096。
我在最新的提交中暂时解决了这个问题
