### ISSUE TITLE
二维码过期了

### ISSUE THREAD

**Issue by RobotJohns** [Soulter/QQChannelChatGPT#10]
二维码过期了，有没有号码

**Comment by Soulter** [comment]
抱歉最近有点忙，忘记过期了。已更新Readme.md~
![1764D0DC39D14FD799DAF4C064E58F63](https://user-images.githubusercontent.com/37870767/212687933-fce63c8c-883a-40e4-8dad-1132559e2eda.jpg)

**Comment by RobotJohns** [comment]
感谢

Soulter ***@***.***> 于2023年1月16日周一 21:22写道：
