### ISSUE TITLE
QQ部署到频道里面用不了

### ISSUE THREAD

**Issue by louis26wq** [Soulter/QQChannelChatGPT#101]
管理者QQ频道用户号不知道在哪里找。
频道里 ！和@  都不搭理，，，
QQ号在qq群里和qq私聊都会回复。

但是在群里@  ！  都没任何反映。

**Comment by louis26wq** [comment]
看到群里讨论的了，，，
可能是因为手表模式登录的，没有频道

**Comment by Soulter** [comment]
是的，我也是昨天才知道（
