### ISSUE TITLE
newbing库建议来源改为可显示 可不显示

### ISSUE THREAD

**Issue by sumingyd** [Soulter/QQChannelChatGPT#102]
QQ群里显示来源太乱了。
我看有人希望显示，不如直接做成个开关吧。可配置开启或关闭

**Comment by sumingyd** [comment]
实际内容只有3行

来源9行。。。。

**Comment by sumingyd** [comment]
![QQ截图20230522223221](https://github.com/Soulter/QQChannelChatGPT/assets/45293856/19018466-bbf2-41a2-822f-dd8e83e3954d)

**Comment by Soulter** [comment]
新版本超过100个字符长度后会折叠形式发送，应该可以解决这个问题（？）
