### ISSUE TITLE
不知道是go-cqhttp机器人的问题还是这边的代码问题，gocq用一会儿就用不了了。

### ISSUE THREAD

**Issue by louis26wq** [Soulter/QQChannelChatGPT#103]
看不懂代码，不知道是什么意思，，，
一个进程同时开了频道机器人和QQ机器人。
出现下面的红字后。
go-cqhttp机器人没反应了，qq频道机器人还是正常的。

[05-23 11:28:11] [INFO] [GOCQ]: 回复GOCQ消息: [GPT]无闪屏LED灯相对于传统灯泡或荧光灯等光源来说确实...
ERROR: Task exception was never retrieved
future: <Task finished name='Task-2' coro=<CQHTTP.ws_event() done, defined at /usr/local/python3/lib/python3.11/site-packages/nakuru/application.py:56> exception=TypeError('can only concatenate str (not "dict") to str')>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/nakuru/application.py", line 71, in ws_event
    received_data = NoticeTypes[received_data["notice_type"]].parse_obj(received_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ChannelUpdated
old_info -> creator_id
  field required (type=value_error.missing)
new_info -> creator_id
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/nakuru/application.py", line 80, in ws_event
    logger.error("Protocol: data parse error: " + received_data)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "dict") to str
[05-23 11:31:31] [INFO] [QQ频道]: 收到消息：<@!3826959282XXXXXXXXXXX> 你在吗

![image](https://github.com/Soulter/QQChannelChatGPT/assets/80579925/10576353-fe19-420e-a3be-be1f78e250b1)

**Comment by louis26wq** [comment]
重启python3 main.py  又能正常用。好奇怪，挂后台睡觉去了，明天早上再看看是否正常

**Comment by louis26wq** [comment]
早上试了下，没问题。

**Comment by Ricky-Ay** [comment]
你这个到源码里改下代码就好了，可以用GPT帮你改

**Comment by Soulter** [comment]
破案了，上游依赖库(nakuru)的一个小问题。已经提交拉取请求，通过之后就能解决了。

**Comment by Soulter** [comment]
上游侧已解决。
可以使用如下指令更新（更换）: 
```bash
pip uninstall nakuru-project-idk
pip install nakuru-project -i https://pypi.org/simple
```
