### ISSUE TITLE
QQ群长文本回复可否以转发的形式折叠？

### ISSUE THREAD

**Issue by DannyLI0319** [Soulter/QQChannelChatGPT#104]
RT，相当于转发聊天记录的形式回复，避免太长的回复刷屏

**Comment by Soulter** [comment]
好的，将会加入此功能

**Comment by Soulter** [comment]
新版本已加入。当字符长度（`utf-8`编码）大于100时，会折叠发送。

**Comment by DannyLI0319** [comment]
100字符会非常短，基本3行的回复都会被折叠。体感200字符会比较合适点。或者是否可以改成可配置？

**Comment by Soulter** [comment]
![image](https://github.com/Soulter/QQChannelChatGPT/assets/37870767/b211846e-2f58-4a5d-8b1b-ba86d81434f8)

新版本启动之后可在`cmd_config.json`下将`qq_forward_threshold`自定义数值。默认200
