### ISSUE TITLE
可否支持GPT-4的API

### ISSUE THREAD

**Issue by DannyLI0319** [Soulter/QQChannelChatGPT#106]
可否支持GPT-4的API？
![image](https://github.com/Soulter/QQChannelChatGPT/assets/120266145/95c4fcbe-ae23-4f97-bb6c-dc5c1a3633f5)

其他项目供参考：
https://github.com/RockChinQ/QChatGPT
![image](https://github.com/Soulter/QQChannelChatGPT/assets/120266145/21f75dfc-17c5-4101-bbe4-45321fa7644f)

**Comment by Soulter** [comment]
一直都支持，在机器人config把model改成gpt-4就行
