### ISSUE TITLE
QQ 群的入群提醒可以关闭吗？

### ISSUE THREAD

**Issue by DannyLI0319** [Soulter/QQChannelChatGPT#113]
因为新人进来看到会一脸懵逼，然后输help好多指令看不懂，所以想用QQ 助手的入群提醒自己配置，这样的话能把这个程序自带的关闭吗？就是突然下面的那个

![Screenshot_2023-06-15-14-35-49-261_com.tencent.mobileqq-edit.jpg](https://github.com/Soulter/QQChannelChatGPT/assets/120266145/377024ee-23e8-41bd-877d-68a28d16b68b)

**Comment by Soulter** [comment]
可以关闭。
在`cmd_config.json`文件下将
`gocq_react_group_increase` true设为false，然后保存即可。
不需要重启
