### ISSUE TITLE
error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

### ISSUE THREAD

**Issue by WdmD114514** [Soulter/QQChannelChatGPT#116]
提示是可能是代理错误，但是在配置文件里已经更改了config的代理地址，软件是v2rayn，是key有问题还是代理出错了呢(｀ﾍ´)=3

**Comment by Soulter** [comment]
估计是配置文件格式不对

**Comment by Soulter** [comment]
![image](https://github.com/Soulter/QQChannelChatGPT/assets/37870767/d656d9b2-086c-4ae0-8cb9-4f0ae0fc0b7e)

**Comment by WdmD114514** [comment]
![Snipaste_2023-06-19_19-09-26](https://github.com/Soulter/QQChannelChatGPT/assets/119395996/93bb362e-9398-407b-b425-a8a0a21c458c)

**Comment by WdmD114514** [comment]
![Snipaste_2023-06-19_19-09-52](https://github.com/Soulter/QQChannelChatGPT/assets/119395996/eb8eed5a-003c-4d71-b3f4-0da74d9af9ae)

**Comment by WdmD114514** [comment]
emmm还是同样的报错

**Comment by Soulter** [comment]
删掉chatgpt_key_record文件然后重启试试

**Comment by WdmD114514** [comment]
已solve，非常感谢Thanks♪(･ω･)ﾉ
