### ISSUE TITLE
QQ频道机器人

### ISSUE THREAD

**Issue by eewxzhang** [Soulter/QQChannelChatGPT#118]

**Comment by eewxzhang** [comment]
QQ频道机器人在哪里配置正式环境接口呢？搜索代码都没有到到url位置，谢谢！
https://api.sgroup.qq.com/

**Comment by Soulter** [comment]
只需要将机器人的appid和token放到配置文件的相应位置就行了
https://github.com/Soulter/QQChannelChatGPT/wiki/%E4%BA%8C%E3%80%81%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE
