### ISSUE TITLE
第三方依赖库未完全安装完毕，请退出程序重试。

### ISSUE THREAD

**Issue by Pwn1996** [Soulter/QQChannelChatGPT#120]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
依赖库安装完毕。
Field "model_show" has conflict with protected namespace "model_"
第三方依赖库未完全安装完毕，请退出程序重试。

**Comment by Soulter** [comment]
已解决。
原因：https://github.com/Lxns-Network/nakuru-project/issues/20
修复方案：
执行以下命令
```
pip3 install pydantic==1.10.4
```
