### ISSUE TITLE
出现ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Pwn1996** [Soulter/QQChannelChatGPT#122]
![mmexport1688471747715.png](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/4a158304-b0ac-49e9-a5f6-6ce8ae1ebfe0)

**Comment by Soulter** [comment]
pip3 install -r requirements.txt

**Comment by Pwn1996** [comment]
感谢
