### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Kelejun** [Soulter/QQChannelChatGPT#123]
```
依赖库安装完毕。
/home/azureuser/.local/lib/python3.8/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_show" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Not available Python version: 3.8.10
第三方依赖库未完全安装完毕，请退出程序重试
```
报错如上，且根据 #120 的方法无法解决，如下：

```
>  pip3 install pydatic==1.10.4
ERROR: Could not find a version that satisfies the requirement pydatic==1.10.4 (from versions: none)
ERROR: No matching distribution found for pydatic==1.10.4
```

**Comment by Soulter** [comment]
> ```
> 
> 依赖库安装完毕。
> 
> /home/azureuser/.local/lib/python3.8/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_show" has conflict with protected namespace "model_".
> 
> 
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
> 
>   warnings.warn(
> 
> Not available Python version: 3.8.10
> 
> 第三方依赖库未完全安装完毕，请退出程序重试
> 
> ```
> 
> 报错如上，且根据 #120 的方法无法解决，如下：
> 
> 
> 
> ```
> 
> >  pip3 install pydatic==1.10.4
> 
> ERROR: Could not find a version that satisfies the requirement pydatic==1.10.4 (from versions: none)
> 
> ERROR: No matching distribution found for pydatic==1.10.4
> 
> ```
> 
> 

抱歉，我的问题，应该是pydantic
