### ISSUE TITLE
用bing语言模型失败

### ISSUE THREAD

**Issue by Pwn1996** [Soulter/QQChannelChatGPT#124]
![360截图20230802202810387](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/d3ad644c-cdc0-4bcc-a413-2cba3dcce04a)

**Comment by Soulter** [comment]
可以尝试用逆向ChatGPT库。bing由于原作者不再维护，因此可能不可用了

**Comment by Pwn1996** [comment]
> 可以尝试用逆向ChatGPT库。bing由于原作者不再维护，因此可能不可用了

用逆向库的话总是出现代码429和401错误![Screenshot_2023-08-03-21-29-16-099_com.tencent.mobileqq.jpg](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/eeee9676-c489-42ca-a50d-0883bf7ac86f)

![Screenshot_2023-08-03-21-30-38-525_com.tencent.mobileqq.jpg](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/2c987af7-6fef-40b0-ac74-47bf1fbc7e5b)

**Comment by Soulter** [comment]
1. 401是因为access token过期了，可以重新从`https://chat.openai.com/api/auth/session`获取。
2. Field Missing可能是因为库的版本用的是旧版，请执行
```
pip3 show pydantic
pip3 show revChatGPT
```
然后提供一下版本号

**Comment by Pwn1996** [comment]
![360截图20230803220925875](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/6725abfd-6c2f-4641-addf-71fe587e6d1e)

**Comment by RockChinQ** [comment]
> 
> ![360截图20230803220925875](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/6725abfd-6c2f-4641-addf-71fe587e6d1e)
> 
> 

revChatGPT版本太低了

用 pip3 install revChatGPT -U 更新一下

**Comment by Pwn1996** [comment]
![7](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/a959b1c7-f554
![8](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/eacb78ef-593c-4e15-9c57-d380f9c76d7a)
-4c89-b781-9efa2108e007)

**Comment by Pwn1996** [comment]
![7](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/570fe3ca-6596-433a-aa6d-e469fda1c37d)
![8](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/2afaa6d0-8d32-4e40-a3fb-dc226e015c0f)

看看项目目录下的requierments.txt文件，如果revChatGPT对应的是你目前的`5.0.4`版本，那就更新一下项目（在聊天处输入`/update latest`指令更新），更新成功后再重启程序。如果更新失败，那就直接修改requierments.txt那个版本为6.8.6

**Comment by Soulter** [comment]
![image](https://github.com/Soulter/QQChannelChatGPT/assets/37870767/349f81fd-4a99-47db-8411-e681e521f082)

**Comment by Pwn1996** [comment]
逆向库弄好了，感谢！我还想用官方key，但是又出现下面的情况![mmexport1691111870573.png](https://github.com/Soulter/QQChannelChatGPT/assets/101928575/d04f9a1a-603d-4c0e-8fbd-c51cbd55d88e)
