### ISSUE TITLE
接口请求异常，错误代码: 403

### ISSUE THREAD

**Issue by dislove** [Soulter/QQChannelChatGPT#13]
[botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/channels/138017643/messages, 错误代码: 403, 返回内容: {'code': 304003, 'message': 'url not allowed'}, trace_id:b6402c0de52e572c3baa63bf5e97b036
部署好了，但是从客户端qq发消息过去后提示这个

**Comment by Soulter** [comment]
已在QQ解决

**Comment by xionghaizhi** [comment]
> 已在QQ解决

需要重新登陆？拉取最新的代码还是报错

**Comment by Soulter** [comment]
看报错可以知道原因，QQ频道禁止机器人发送带有未备案的网页链接，应该是一个概率性事件(?
