### ISSUE TITLE
调用语言模型例程时出现异常。原因: 'NoneType' object has no attribute 'call_soon_threadsafe'

### ISSUE THREAD

**Issue by RoyH0427** [Soulter/QQChannelChatGPT#132]
回复QQ频道消息: 调用语言模型例程时出现异常。原因: 'NoneType' object has no attribute 'call_soon_threadsafe'
调用语言模型例程时出现异常。原因: 'NoneType' object has no attribute 'call_soon_threadsafe' None
E:\codes\QQChannelChatGPT-Launcher\QQChannelChatGPT\cores\qqbot\core.py:663: RuntimeWarning: coroutine 'ProviderRevEdgeGPT.text_chat' was never awaited
  return

**Comment by Soulter** [comment]
bing模型目前已无法正常使用（原作者不再更新），可以暂时先用一下Claude，官方ChatGPT或者HuggingChat
