### ISSUE TITLE
windows系统launcher部署出错，第三方库未完全安装完毕

### ISSUE THREAD

**Issue by cyrandom** [Soulter/QQChannelChatGPT#133]
launcher启动后：
欢迎来到QQChannelChatGPT项目的Windows启动向导，正在进行依赖检查
当前版本: 6b85139e3aa6b41fc0c706c197814d4c71c642ad
最新版本: 6b85139e3aa6b41fc0c706c197814d4c71c642ad
已是最新版本
如果您是初次启动, 请先在QQChannelChatGPT/configs/config.yaml填写或者修改相关机器人配置! 等待5秒继续...
正在启动...
正在更新三方依赖库...
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
依赖库安装完毕。
found undefined alias 'default'
  in "C:\Users\cyl\Desktop\cybot\sub-launcher\QQChannelChatGPT/configs/config.yaml", line 49, column 13
第三方依赖库未完全安装完毕，请退出程序重试。

报错位置是粘贴进config.yaml的servers部分。
      middlewares:
        <<: *default # 引用默认中间件

**Comment by YLchen22** [comment]
补充一下，如果servers这段注释掉的话就没有报错。但是与GO-CQHTTP通信失败。

**Comment by Soulter** [comment]
Hi，servers那段不需要取消注释。然后请确保打开了与launcher同目录下的gocq程序( 填好qq和密码之后 )
