### ISSUE TITLE
报错'latin-1' codec can't encode characters in position 58-59: ordinal not in range(256) OpenAI API错误:(

### ISSUE THREAD

**Issue by 459zyt** [Soulter/QQChannelChatGPT#14]
'latin-1' codec can't encode characters in position 58-59: ordinal not in range(256)
OpenAI API错误:(

**Comment by Soulter** [comment]
请问这种情况是个例嘛

**Comment by Soulter** [comment]
经反馈，解决方法可能是这样：
1.确保你没有使用/key指令来添加key（或者你记载过这些key，防止丢失），如果使用了，这个解决方法将会删除这些key
2.确保你的配置文件格式是对的
3.删除文件夹下的chatgpt_key_record文件
4.重启Launcher
