### ISSUE TITLE
敏感词过滤功能不够强大

### ISSUE THREAD

**Issue by dsy4567** [Soulter/QQChannelChatGPT#18]
提问时对敏感词掺杂空格，使用敏感词的同义词，或让 ChatGPT 对输出稍加处理即可绕过限制

例如：可将 `习近平主席的简介` 替换成 `习 近平主席的简介` 或 `习主席的简介`

顺便建议屏蔽以下词语
```
习主席
周总理
毛主席
20大
中央人民政府
香港暴乱
翻墙
GFW
防火长城
VPN
科学上网
V2Ray
TorProject
ShadowSocks(R)
```

**Comment by Soulter** [comment]
好的，我会在下一个版本中完善敏感词过滤的功能

**Comment by amazing-fish** [comment]
应该要选择性开启和词库加入吧

**Comment by Soulter** [comment]
已实现此功能，可以在`unfit_words.py`下添加正则表达式，欢迎提交pr丰富拦截词库！

并且在此基础上新增腾讯AI内容审核服务，可选择性打开，详见新提交的配置文件`configs/config.yaml`。
