### ISSUE TITLE
需要安装哪些依赖

### ISSUE THREAD

**Issue by miloce** [Soulter/QQChannelChatGPT#2]

**Comment by Soulter** [comment]
忘记在README.md上说明了()
需要安装的依赖：
- `qq-botpy` （QQ频道官方Python SDK）
- `openai` (OpenAI 库)

**Comment by miloce** [comment]
![Screenshot_2022_1210_153024](https://user-images.githubusercontent.com/82767574/206838325-1346f417-c844-4a4f-a764-f9f7e733538d.png)
安装好依赖后，这个报错怎么办

**Comment by Soulter** [comment]
原因是缺少了项目的util文件夹，抱歉之前忘记提交这个了，我现在已经把这个提交上去了，重新clone一遍就行
![image](https://user-images.githubusercontent.com/37870767/206839071-88a4f687-e6d4-4eda-8383-0a748853c4e9.png)

**Comment by miloce** [comment]
好的👌
