### ISSUE TITLE
请问这是为什么，一句话都不会回答，除了你好

### ISSUE THREAD

**Issue by amazing-fish** [Soulter/QQChannelChatGPT#21]
请问这是为什么，一句话都不会回答，除了你好
[WARNING] ([connectionpool.py:812](http://connectionpool.py:812/))urlopen Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by ‘NewConnectionError(’<urllib3.connection.HTTPSConnection object at 0x0000020809A84CD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝 试失败。‘)’: /v1/chat/completions
[System-Err] OpenAI API错误。原因如下:
Error communicating with OpenAI: HTTPSConnectionPool(host=‘[api.openai.com](http://api.openai.com/)’, port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError(‘<urllib3.connection.HTTPSConnection object at 0x0000020809A9A9A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。’))
[ERROR] ([http.py:73](http://http.py:73/))_handle_response [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/743294207149637636/messages, 错误代码: 403, 返回内容: {‘code’: 304003, ‘message’: ‘url not allowed’}, trace_id:17b87c968c0f64875c9179af44529e05

**Comment by Soulter** [comment]
可能是最近有重大会议的原因，OpenAI的API在大陆地区全部被墙，需要挂梯子才能连接。
可以试一下挂梯子再重启程序。

**Comment by amazing-fish** [comment]
我挂了，全局也试过

**Comment by Soulter** [comment]
是用逆向的ChatGPT还是官方的API

**Comment by amazing-fish** [comment]
> 是用逆向的ChatGPT还是官方的API

我用的官方的，另外，当我用逆向的时候，会在过程中闪退

**Comment by amazing-fish** [comment]
> 是用逆向的ChatGPT还是官方的API

况且我的梯子是可以访问chatgpt的

**Comment by ilila** [comment]
same problem，期待仓库主的解决方法

**Comment by Soulter** [comment]
已提交程序V2.5.5.1。

更新后，请在`config.yaml`添加相关字段
```
# 正向代理，将mask改为localhost:你的代理软件提供的端口，如7890。不用的时候记得用#注释掉
# 例：http://localhost:7890
http_proxy: mask
https_proxy: mask
```

**Comment by Soulter** [comment]
![image](https://user-images.githubusercontent.com/37870767/222944708-bcbd813a-9118-495c-bb44-0ab9d939ff60.png)

**Comment by amazing-fish** [comment]
> 已提交程序V2.5.5.1。
> 
> 更新后，请在`config.yaml`添加相关字段
> 
> ```
> # 正向代理，将mask改为localhost:你的代理软件提供的端口，如7890。不用的时候记得用#注释掉
> # 例：localhost:7890
> http_proxy: mask
> https_proxy: mask
> ```

![image](https://user-images.githubusercontent.com/71763696/222952495-b002830d-f7b4-4082-b49a-0b44ce96d1ea.png)
报错后闪退

**Comment by amazing-fish** [comment]
点启动器会出现这个：
![image](https://user-images.githubusercontent.com/71763696/222953320-12a947f9-02b7-4551-871e-3953f582cce2.png)
点bot.exe会在收到消息后出现：
![image](https://user-images.githubusercontent.com/71763696/222953371-7351cea5-60c7-41c9-a371-788f72dff674.png)

**Comment by amazing-fish** [comment]
> 点启动器会出现这个： ![image](https://user-images.githubusercontent.com/71763696/222953320-12a947f9-02b7-4551-871e-3953f582cce2.png) 点bot.exe会在收到消息后出现： ![image](https://user-images.githubusercontent.com/71763696/222953371-7351cea5-60c7-41c9-a371-788f72dff674.png)

第一个问题已解决，第二个是主要问题，我用的代理：
![image](https://user-images.githubusercontent.com/71763696/222953540-17cec733-bb10-4812-b7fb-a4fbc0fb4fef.png)
用19180和19181，以及加不加引号都不行：
![image](https://user-images.githubusercontent.com/71763696/222953601-e73b5fc2-cb70-4ba0-8b3f-54ce05d0a54d.png)

**Comment by Soulter** [comment]
Python3.7+版本在部署正向代理时应在代理链接前加上`http://`

如

```
http_proxy: http://localhost:7890
https_proxy: [mask](http://localhost:7890)
```
