### ISSUE TITLE
key没有问题，提示api错误

### ISSUE THREAD

**Issue by xuniyu** [Soulter/QQChannelChatGPT#25]
![image](https://user-images.githubusercontent.com/83167616/222945248-7b212d27-f5f2-41dc-a323-0ae55624efbf.png)

**Comment by Soulter** [comment]
是从老版本更新过来的嘛？
删除一下所在目录的data.db，然后重启程序

**Comment by xuniyu** [comment]
> 是从老版本更新过来的嘛？ 删除一下所在目录的data.db，然后重新启动程序

我直接删除重装的，覆盖安装机器人不动了，然后就删了

**Comment by Soulter** [comment]
> ![image](https://user-images.githubusercontent.com/83167616/222945248-7b212d27-f5f2-41dc-a323-0ae55624efbf.png)

这里的数据结构还是以前的，你检查一下data.db有没有删除

**Comment by xuniyu** [comment]
> > ![image](https://user-images.githubusercontent.com/83167616/222945248-7b212d27-f5f2-41dc-a323-0ae55624efbf.png)
> 
> 这里的数据结构还是以前的，你检查一下data.db有没有删除

data.db在哪，在文件夹里面吗，没找到，还有就是我没有创建数据库，这个咋删勒

**Comment by Soulter** [comment]
和main.py同级目录，数据库是程序自己创建的

**Comment by xuniyu** [comment]
跟main.py  同级目录吗，好像没有 这个
![image](https://user-images.githubusercontent.com/83167616/222945876-87bbdca6-4a58-4692-8a9d-c0aac976ed07.png)

**Comment by xuniyu** [comment]
通过/reset 重置之后就可以用了，但感觉接口还是3，有没有啥方法全部重置呀或者是怎么看调用的接口是多少

**Comment by Soulter** [comment]
/gpt查看调用的模型。如果是3.5-turbo就是正常的。
