### ISSUE TITLE
centos7运行报错了，python版本为3.9.10

### ISSUE THREAD

**Issue by wuhonghui123** [Soulter/QQChannelChatGPT#29]
[root@VM-12-5-centos QQChannelChatGPT-master]# python3 -V
Python 3.9.10
[root@VM-12-5-centos QQChannelChatGPT-master]# python3 main.py
程序PID:5007
Traceback (most recent call last):
  File "/root/qqchangpt/QQChannelChatGPT-master/main.py", line 175, in <module>
    check_env()
  File "/root/qqchangpt/QQChannelChatGPT-master/main.py", line 152, in check_env
    cfg = yaml.safe_load(ymlfile)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/root/qqchangpt/QQChannelChatGPT-master/configs/config.yaml", line 8, column 1
expected <block end>, but found '<block mapping start>'
  in "/root/qqchangpt/QQChannelChatGPT-master/configs/config.yaml", line 51, column 3

**Comment by Soulter** [comment]
初步判断时配置文件格式的问题。
请提供一下配置文件内容（关键信息请删除或打码）

**Comment by wuhonghui123** [comment]
# 如果你不知道怎么部署，请务必查看https://soulter.top/posts/qpdg.html

# 注意：已支持多key自动切换，方法：
# key:
#   - sk-xxxxxx
#   - sk-xxxxxx
# 在下方非注释的地方使用以上格式
openai:
  key: 
    - sk-ctdEyJKa6Mb8ptomijLvT
    
  # 这里是GPT配置，语言模型默认使用gpt-3.5-turbo
  chatGPTConfigs:
    model: gpt-3.5-turbo
    max_tokens: 1500
    temperature: 0.9
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0
    
  total_tokens_limit: 2800

# QQ开放平台的appid和令牌
# q.qq.com
qqbot:
  appid: 102043604
  token: aCPfUZnZ51tFBaH

# 设置是否一个人一个会话
uniqueSessionMode: true

# QChannelBot 的版本，请勿修改此字段，否则可能产生一些bug
version: 2.5 RealChatGPT Ver.

# [Beta] 转储历史记录时间间隔(分钟)
dump_history_interval: 10

# 一个用户只能在time秒内发送count条消息
limit:
  time: 60
  count: 5
# 公告
notice: "此机器人由Github项目QQChannelChatGPT驱动。"

# 是否打开私信功能
# 设置为true则频道成员可以私聊机器人。
# 设置为false则频道成员不能私聊机器人。
direct_message_mode: true

# 系统代理
  http_proxy: 127.0.0.1:8008
  https_proxy: 127.0.0.1:8008

################外带程序（插件）################

# 逆向ChatGPT库
# https://github.com/acheong08/ChatGPT
# 优点：免费（无免费额度限制）；
# 缺点：速度相对慢。OpenAI 速率限制：免费帐户每小时 50 个请求。您可以通过多帐户循环来绕过它
# enable设置为true后，将会停止使用上面正常的官方API调用而使用本逆向项目
#
# 多账户可以保证每个请求都能得到及时的回复。


# 关于account的格式，请你务必认真阅读以下格式。


# account支持email+password、session_token、access_token多种方式登录。
# 如果要使用session_token、access_token登录，直接添加新的一行（注意缩进！） - access_token: xxxxxxx即可
# account:
#   - session_token: xxxxxxxx
#   - access_token: xxxxxxxx
#   - email: 第1个账户
#     password: 第1个账户密码
#   - email: 第2个账户
#     password: 第2个账户密码
#   - ....
# 请严格按照上面这个格式填写。
# 这里免费提供2个账号给大家，不过用的人一定会很多的，所以会造成一些bug，因此还是用自己的账号好一点。
# 需要账号可以联系我。QQ905617992

rev_ChatGPT:
  enable: false
  account:
    - access_token: 
    # - session_token: xxxxxxxx
    - email: d.o.m.her.ry61.7@gmail.com
      password: 11111111
    - email: ca.it.li.nal.o.i.si.o91@gmail.com
      password: 11111111

**Comment by Soulter** [comment]
```
# 系统代理
  http_proxy: 127.0.0.1:8008
  https_proxy: 127.0.0.1:8008
```
这个地方，将前面的空格删去。

改成如下形式：
```
# 系统代理
http_proxy: http://127.0.0.1:8008
https_proxy: http://127.0.0.1:8008
```

**Comment by wuhonghui123** [comment]
多谢了
