### ISSUE TITLE
报错：Max retries exceeded with url: /api/conversation ...

### ISSUE THREAD

**Issue by Zmincrix** [Soulter/QQChannelChatGPT#36]
![image](https://user-images.githubusercontent.com/35093819/224251780-54f4f477-55ed-4994-94fd-f6be38f8f8af.png)

**Comment by Soulter** [comment]
近期openai api被墙，在中国大陆内可能没法直接使用，需要挂梯子。

先升级：

linux或源码运行的用户：使用pip3 install --upgrade revChatGPT命令升级逆向库版本。
windows版本用户：重启启动器更新。

升级完之后，
已提交程序V2.5.5.1。

更新后，请在config.yaml添加相关字段来设置正向代理。（因为直接连梯子可能没有用，当然你也可以试试）

```
# 正向代理，将mask改为localhost:你的代理软件提供的端口，如7890。不用的时候记得用#注释掉
# 例：http://localhost:7890
http_proxy: mask
https_proxy: mask
```
