### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#47]
当前版本: 2.7
发现新版本: 2.8
文件大小: 0.0001392364501953125MB
正在更新文件...
division by zero
更新失败，请在https://github.com/Soulter/QQChannelChatGPT上提交issue说明问题！或者添加QQ：905617992
请按任意键继续. . .

**Comment by Soulter** [comment]
刚刚误删文件了，重试一下
