### ISSUE TITLE
从源码端解决每次更新会覆盖用户配置文件的问题

### ISSUE THREAD

**Issue by Mushan3420** [Soulter/QQChannelChatGPT#56]
每次更新都会覆盖配置文件，建议源码里面的示例配置叫 config.sample.yaml，可复制一份，重命名为 config.yaml，用于自定义配置。

另外，如果写个安装向导，安装时引导用户输入必要的 API 和 KEY，自动生成 config.yaml，体验更佳~

**Comment by Soulter** [comment]
已逐步实现此功能。
