### ISSUE TITLE
Bing 激活报错

### ISSUE THREAD

**Issue by SighOfFrostmourne** [Soulter/QQChannelChatGPT#62]
revEdgeGPT:true 之后报
File "/root/qqchangpt/QQChannelChatGPT/addons/revEdgeGPT/revedgegpt.py", line 9, in __init__
    with open('./cookies.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './cookies.json'

**Comment by Mushan3420** [comment]
NewBing接入（需要在QQChannelChatGPT目录下添加cookies.json文件，cookies.json文件获取教程https://github.com/acheong08/EdgeGPT）

**Comment by SighOfFrostmourne** [comment]
感谢大佬，可以了！
