### ISSUE TITLE
信息过长报错

### ISSUE THREAD

**Issue by DannyLI0319** [Soulter/QQChannelChatGPT#64]
好像回复比较长会报错，有办法做到折叠转发或者信息拆分成几条发吗？
![image](https://user-images.githubusercontent.com/120266145/229264556-1024fc87-c8cd-4c94-ab4b-49b6d302f0a1.png)

**Comment by Soulter** [comment]
#40

**Comment by Soulter** [comment]
新版本已解决，欢迎去release页面重新下载新的安装器
