### ISSUE TITLE
update指令

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#68]
![image](https://user-images.githubusercontent.com/117758199/229535137-d1724058-e566-4f26-9166-d9029516784b.png)
QQ上也无消息回复

**Comment by Soulter** [comment]
抱歉，之前的fix版本的安装器内部的git分支选错了（选成了重构用的分支），可能需要重新下载一下安装器，最好放在一个新的文件夹下。

**Comment by YSDiting** [comment]
![image](https://user-images.githubusercontent.com/117758199/229540547-697e50a2-035c-4b3d-b476-90657468f9ad.png)
重新安装新的安装器之后

**Comment by Soulter** [comment]
正常现象，国内对Github有DNS污染。过几分钟重试就行，或者梯子

**Comment by YSDiting** [comment]
谢谢大佬
