### ISSUE TITLE
功能建议：添加备用key

### ISSUE THREAD

**Issue by InternetBugs** [Soulter/QQChannelChatGPT#7]
希望可以添加多个openai的key进行备用，当目前正在使用的key余额不足时自动删除当前key并使用备用key
在QQ 聊天机器人和tg机器人都看见了这个功能，觉得挺有用的

**Comment by Soulter** [comment]
感谢你的建议~ 
我在最新的提交中已经增加了这个功能，使用方法如下：
在`configs/config.yaml`的`openai`-> `key`下，使用如下格式添加备用key：
![image](https://user-images.githubusercontent.com/37870767/208229591-a4202ae9-0492-4cd6-848b-82585069ba2b.png)

程序会将其封装成一个列表，并存储相关使用数据到本地文件中来使用。
可以在频道中使用指令`/status`查看配额。
