### ISSUE TITLE
Bing无法显示参考文献

### ISSUE THREAD

**Issue by DannyLI0319** [Soulter/QQChannelChatGPT#70]
大佬可否把这个加上去？或者作为一个配置可选项

**Comment by Mushan3420** [comment]
我也希望加上去，但是网址需要加入白名单，不然就会报错。比如：

> [RevEdgeGPT] 好的，我用到的参考资料有：
> 
> -  Bing Translator: http://www.bing.com/translator/?ref=TThis&text=清明 by 杜牧&from=&to=ru
> -  栗子的翻译笔记 - 清明（杜牧） - 知乎: https://zhuanlan.zhihu.com/p/61434128
> -  杜牧《清明》英文版 - 知乎: https://zhuanlan.zhihu.com/p/362211669
> 
> 你还有什么问题吗？😊
> [ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2926067677496743208/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': '{"beat_reason":21000,"beat_detail":"其他"}'}, trace_id:a8aca4b91bb8c69b147465f79f4141b3
> [System-Error] 回复QQ消息失败
> QQ频道API错误: 
> {"beat_reason":21000,"beat_detail":"其他"}
> [ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2926067677496743208/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': '{"beat_reason":21000,"beat_detail":"其他"}'}, trace_id:f033527ae20fc3acce69178bdf4384ac
> [System-Error] 回复QQ消息失败
> [INFO]  (gateway.py:54)on_closed        [botpy] 关闭, 返回码: 4009, 返回信息: Session timed out
> [INFO]  (connection.py:59)multi_run     [botpy] 最大并发连接数: 1, 启动会话数: 1
> [INFO]  (client.py:236)bot_connect      [botpy] 会话启动中...
> [INFO]  (gateway.py:110)ws_connect      [botpy] 启动中...
> [INFO]  (gateway.py:169)ws_resume       [botpy] 重连启动...
> [INFO]  (gateway.py:85)on_message       [botpy] 机器人重连成功! 
> [INFO]  (gateway.py:217)_send_heart     [botpy] 心跳维持启动...
> [RevEdgeGPT] 好的，我用到的参考资料有：
> 
> -  Bing Translator: http://www.bing.com/translator/?ref=TThis&text=清明 by 杜牧&from=&to=ru
> -  栗子的翻译笔记 - 清明（杜牧） - 知乎: https://zhuanlan.zhihu.com/p/61434128
> -  杜牧《清明》英文版 - 知乎: https://zhuanlan.zhihu.com/p/362211669
> 
> 你还有什么问题吗？😊
> [ERROR] (http.py:73)_handle_response    [botpy] 接口请求异常，请求连接: https://api.sgroup.qq.com/dms/2926067677496743208/messages, 错误代码: 500, 返回内容: {'code': 2000004, 'message': '{"beat_reason":21000,"beat_detail":"其他"}'}, trace_id:a8aca4b91bb8c69b147465f79f4141b3
> [System-Error] 回复QQ消息失败
> QQ频道API错误: 
> {"beat_reason":21000,"beat_detail":"其他"}                                                                               

作者看看能不能有变通的办法吧

**Comment by Soulter** [comment]
新版已增加。

**Comment by sumingyd** [comment]
> 新版已增加。

消息来源这个是否可以加个选项，，可显示可不显示。。。QQ群里显示来源 太乱了。
