### ISSUE TITLE
 [System] 创建rev_ChatGPT负载失败: PUID is required

### ISSUE THREAD

**Issue by Mushan3420** [Soulter/QQChannelChatGPT#76]
用 session_token 登录 Chat GPT，启动后报错： [System] 创建rev_ChatGPT负载失败: PUID is required，无法回复QQ消息，就回复一个 None，如何解决？

**Comment by Soulter** [comment]
用access_token

**Comment by Mushan3420** [comment]
如何获取 access_token ？

**Comment by Soulter** [comment]
https://chat.openai.com/api/auth/session
