### ISSUE TITLE
【功能需求】自定义指令

### ISSUE THREAD

**Issue by Mushan3420** [Soulter/QQChannelChatGPT#78]
如果能实现自定义指令和回复就好了。比如：/add 添加指令，C=指令字符 | R=回复文字，然后，机器人就接受了这条指令。

> 用户：/add
> Bot： 请按以下格式添加指令：C=指令字符 | R=回复文字
> 用户：C=XXXX | R=YYYY
> Bot： 您添加的指令是 XXXX，该指令的回复是 YYYY，是否确认？回复Y确认，回复N取消。
> 用户：Y
> Bot：指令添加成功，您可以发送 /XXXX 来触发指令。

备注：
1.指令添加功能需要设法限制仅有该机器人开发者可用，其他人禁止触发。如果不能实现，可以退而求其次，写配置文件来添加指令。
2. 添加的自定义指令可供全体成员使用，且在任何模型中均可使用，不受影响。

**Comment by Soulter** [comment]
已实现。
更新后输入`/keyword`了解更多
