### ISSUE TITLE
频道里的所有用户的历史记录会串在一起

### ISSUE THREAD

**Issue by InternetBugs** [Soulter/QQChannelChatGPT#8]
![Screenshot_20221217-224149_QQ](https://user-images.githubusercontent.com/77239633/208247394-142d170c-443b-4773-bd15-4077bd1b96ee.png)
如图，上边的消息不是我发的，但是依然能通过/his查询到

**Comment by Soulter** [comment]
可以在config.yaml中设置是否独立会话，
在config.yaml下将uniqueSessionMode改成true即可

**Comment by InternetBugs** [comment]
哦 看到了
纯属我眼瞎（

**Comment by InternetBugs** [comment]
![Screenshot_20221217-230342_Kiwi Browser~3](https://user-images.githubusercontent.com/77239633/208248309-fb440fa2-21a6-4e37-b6e3-07e2c14a8a49.png)
![Screenshot_20221217-230229_QQ](https://user-images.githubusercontent.com/77239633/208248316-52efa1f3-18cb-4267-8eac-fc5f2999bab0.png)
![Screenshot_20221217-230232_QQ](https://user-images.githubusercontent.com/77239633/208248321-cdfaef9a-fe54-4f23-b397-be2ceb9318fe.png)
已经设置了，也重启了程序和清空了聊天记录，还似乎还是显示频道的聊天记录

**Comment by Soulter** [comment]
我的问题（
代码有一行有点问题，现在已经改了，你可以重新拉一下，或者直接在cores/qqbot/core.py下改代码，将uniqueSession设置为`True`
![image](https://user-images.githubusercontent.com/37870767/208248860-0dbef0ea-d1d7-4f4a-a6c2-c9c3922d3127.png)

**Comment by InternetBugs** [comment]
![Screenshot_20221218-040848_QQ](https://user-images.githubusercontent.com/77239633/208264354-837d506a-d506-4f25-a043-8bef32131053.png)
似乎显示的还是“频道的历史记录”
不过因为半夜没有人，所以没法测试是否是独立会话

**Comment by Soulter** [comment]
昨天代码没改完orz
已在最新的提交中修复
