### ISSUE TITLE
keyword指令

### ISSUE THREAD

**Issue by YSDiting** [Soulter/QQChannelChatGPT#80]
keyword指令在使用OpenAI官方模型的时候会被识别为“赞助key”的指令
[QQBOT] 接收到消息：<@!11620738824688910836> keyword
True (True, '感谢您赞助key，key为官方API使用，请以以下格式赞助:\n/key xxxxx', 'key')

**Comment by Mushan3420** [comment]
要不还是用 command 这个单词吧 @Soulter
