### ISSUE TITLE
rev_edgegpt无法使用

### ISSUE THREAD

**Issue by TBMnaitang** [Soulter/QQChannelChatGPT#87]
cookies路径： C:\QQChannelChatGPT
报错如下：
![`5RUAKUK LFAZCJ`SS U%CT](https://user-images.githubusercontent.com/109024252/232131623-0c060b43-f60d-4485-8627-32e3d8e93911.png)

**Comment by Soulter** [comment]
提示验证失败，你的bing账号申请了new bing吗

**Comment by TBMnaitang** [comment]
申请了并批准了 
![Screenshot_2023-04-15-10-11-59-926_com microsoft bing-edit](https://user-images.githubusercontent.com/109024252/232178244-bf981a86-7d99-416c-861d-b2a756d4649b.jpg)

**Comment by Soulter** [comment]
需要挂梯子，然后需要在配置文件设置正向代理

**Comment by TBMnaitang** [comment]
配置文件和梯子设置如下
![image](https://user-images.githubusercontent.com/109024252/232188437-45772ad3-caef-4c05-b79d-247e5be44fc3.png)
依然存在问题

**Comment by TBMnaitang** [comment]
配置文件和梯子设置如下
![image](https://user-images.githubusercontent.com/109024252/232188708-af80cebf-6620-40a2-a46f-89425ca981e8.png)
依然是同样的问题

**Comment by Soulter** [comment]
1.梯子的节点选国外的
2.cookies.json的内容正确嘛，是在www.bing.com页面下拿到(不能是国内版必应，必应页面上没有出现 国内版 国际版的字样)

**Comment by TBMnaitang** [comment]
梯子节点是国外的
cookies是在这个页面获取的 
![RVHM4NSQWBCN3GUGNA25HQF](https://user-images.githubusercontent.com/109024252/232192826-8265faaf-4a7d-4281-87cd-09ed5cf26967.png)

**Comment by Mushan3420** [comment]
这明显是被重定向到国内必应 cn.bing.com 了，梯子没开起来，或者没生效吗？

**Comment by TBMnaitang** [comment]
重新设置后出现了新的报错
![c65dc931c3b2b7ed5513666ca040f2b1](https://user-images.githubusercontent.com/109024252/232441922-20d38d7b-e576-4694-a93b-5a819d284209.png)

**Comment by Soulter** [comment]
配置文件里面设置系统代理

![image](https://user-images.githubusercontent.com/37870767/232684565-8df39ee5-fbd7-4de9-804a-94f19ea48a1a.png)
