### ISSUE TITLE
报错：ERROR: Could not open requirements file，并且一键部署只能拉取到一个空文件夹

### ISSUE THREAD

**Issue by catnap826** [Soulter/QQChannelChatGPT#88]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/114160227/232226180-aae6ebc5-d26e-4baf-9c06-3895fb55e62b.png">
正在从https://github.com/Soulter/QQChannelChatGPT.git拉取项目...
当前设备使用的网络是否为国内网络？ (y/n): n
正在更新三方依赖库...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'QQChannelChatGPT\\requirements.txt'
WARNING: You are using pip version 21.2.3; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\21891\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
依赖库安装完毕
初次启动, 请先在QQChannelChatGPT/configs/config.yaml填写相关配置! 按任意键继续...

<img width="331" alt="image" src="https://user-images.githubusercontent.com/114160227/232226233-b81afbe4-12ae-44de-981e-8697bf928fc3.png">

目前借助一位大佬打包的文件成功部署。

**Comment by Mushan3420** [comment]
文件夹疑似为空，如果管理员模式还不行，也就是排除因权限不足无法写入文件，那可能是启动器连不上Github。
