### ISSUE TITLE
OpenAI API错误:( 原因如下： local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by InternetBugs** [Soulter/QQChannelChatGPT#9]
![Screenshot_20221218-150110_QQ](https://user-images.githubusercontent.com/77239633/208285787-60d4effa-819b-42a0-9931-bc3b9da8bfb0.png)

如图，必须使用/reset重置消息记录才能正常使用
![Screenshot_20221218-150326_Kiwi Browser~2](https://user-images.githubusercontent.com/77239633/208285827-431d4596-4e83-4171-8727-e1e0d405158e.png)

log内容无异常
以下是配置文件内容
![Screenshot_20221218-150418_Kiwi Browser~2](https://user-images.githubusercontent.com/77239633/208285851-f2763d14-4a8b-4b82-9385-743a8fd522fa.png)

**Comment by InternetBugs** [comment]
是不是total_tokens_limit调太高了
我调成example默认的试试

**Comment by Soulter** [comment]
复现频率高嘛？emmm暂时没找出来原因，按理来说应该会打印出错误来的，如下图，遇到异常第一件事就是print错误出来

![image](https://user-images.githubusercontent.com/37870767/208292898-ae117114-5237-455b-8724-1de01c1b60cf.png)

**Comment by InternetBugs** [comment]
total_tokens_limit调成example的700后就没出现过了
之前我作死弄成5000的时候基本一小时出现一次

**Comment by InternetBugs** [comment]
![Screenshot_20221220-063544_QQ](https://user-images.githubusercontent.com/77239633/208540340-6e38ecd5-e08c-4d15-8541-83663d5f75c2.png)
寄，又复现了

**Comment by Soulter** [comment]
刚刚我这也复现了()
应该是程序请求OpenAI接口的时候网络波动造成请求超时，重新发一遍就好了。
我在新的提交里面加了出问题重新请求的逻辑，应该会有一些改善()

**Comment by InternetBugs** [comment]
这段时间有事忙，忘记有个Issues忘关了（
这边简单观察，似乎已经没有复现这个问题了
