### ISSUE TITLE
启用QQ机器人，远程计算机拒绝网络连接

### ISSUE THREAD

**Issue by Ren-Boo** [Soulter/QQChannelChatGPT#93]
[System] 启用QQ机器人
[ERROR] (base_events.py:1744)default_exception_handler  Task exception was never retrieved
future: <Task finished name='Task-2' coro=<CQHTTP.ws_event() done, defined at C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\nakuru\application.py:56> exception=ClientConnectorError(ConnectionKey(host='127.0.0.1', port=6700, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(22, '远程计算机 拒绝网络连接。', None, 1225, None))>
Traceback (most recent call last):
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\nakuru\application.py", line 58, in ws_event
    async with session.ws_connect(f"{self.baseurl}", headers=self.headers) as ws_connection:
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Liu Lin\AppData\Roaming\Python\Python310\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:6700 ssl:default [远程计算机拒绝网络连 接。]

**Comment by Soulter** [comment]
gocq-http启动了吗，下载的启动器尾号是fix-多少

**Comment by Ren-Boo** [comment]
> gocq-http启动了吗，下载的启动器尾号是fix-多少

launcher-0.0.3-fix-1
开全局代理不会报这个错，但是会提示
OpenAI API错误。原因如下：
连接超时 
前往官方频道反馈~

[System] 启用QQ机器人
[GOCQ-BOT] 接收到消息：1
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
[WARNING]       (connectionpool.py:810)urlopen  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /v1/chat/completions
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
[System-Err] OpenAI API错误。原因如下:
连接超时
[System-Info] 回复QQ消息中...OpenAI API错误。原因如下：
连接超时
前往官方频道反馈~

**Comment by Soulter** [comment]
需要在配置文件正确设置系统代理。
- 加上http的协议头
如下：
```yml
# 系统代理
http_proxy: http://localhost:7890
https_proxy: http://localhost:7890
```

不同的代理软件端口可能不同。Clash是7890.

**Comment by Ren-Boo** [comment]
> 

OK，好了，谢谢大佬
